import json
from typing import List, Dict, Any, Optional
from urllib.parse import urlparse

class PythonCodeGenerator:
    """
    Generates standalone Python scripts from extraction patterns.
    Supports Playwright (for JS-heavy sites) and BeautifulSoup (for static sites).
    """
    
    def __init__(self):
        pass
        
    def generate_script(
        self, 
        url: str, 
        fields: List[str], 
        selectors: Dict[str, Any],
        target: Optional[str] = None
    ) -> str:
        """Generate a complete, runnable Python script"""
        domain = urlparse(url).netloc
        
        # Determine if we should use Playwright or BeautifulSoup
        # For now, we'll default to Playwright as it's more universal
        return self._generate_playwright_script(url, fields, selectors, target)
        
    def _generate_playwright_script(
        self, 
        url: str, 
        fields: List[str], 
        selectors: Dict[str, Any],
        target: Optional[str] = None
    ) -> str:
        """Generate a Playwright-based scraper script"""
        
        # Format selectors for the script
        selectors_json = json.dumps(selectors, indent=4)
        fields_json = json.dumps(fields, indent=4)
        
        script = f'''"""
Standalone Scraper for {domain if 'domain' in locals() else url}
Generated by Universal Scraper

Target: {target if target else 'General Data'}
Fields: {', '.join(fields)}
"""

import asyncio
import json
from typing import List, Dict, Any
from playwright.async_api import async_playwright

# Extraction Pattern
SELECTORS = {selectors_json}
FIELDS = {fields_json}

async def scrape_page(url: str) -> List[Dict[str, Any]]:
    """Scrape data from the given URL using Playwright"""
    results = []
    
    async with async_playwright() as p:
        # Launch browser
        browser = await p.chromium.launch(headless=True)
        context = await browser.new_context(
            user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
        )
        page = await context.new_page()
        
        print(f"Navigating to {{url}}...")
        await page.goto(url, wait_until="networkidle", timeout=60000)
        
        # Wait for content to load
        await page.wait_for_timeout(2000)
        
        # Extract items
        # We look for the container/repeating element if it exists in rules
        # In our deterministic rules, we often have a 'container' or we use the first field's selector to find items
        
        # Basic extraction logic using the provided selectors
        # This is a simplified version of the internal deterministic engine
        
        extracted_items = []
        
        # Try to find how many items there are by looking at the first field
        if FIELDS:
            first_field = FIELDS[0]
            selector_info = SELECTORS.get(first_field)
            if selector_info:
                selector = selector_info if isinstance(selector_info, str) else selector_info.get('selector')
                if selector:
                    elements = await page.query_selector_all(selector)
                    print(f"Found {{len(elements)}} potential items")
                    
                    for i in range(len(elements)):
                        item = {{}}
                        for field in FIELDS:
                            field_selector_info = SELECTORS.get(field)
                            if not field_selector_info:
                                item[field] = None
                                continue
                                
                            field_selector = field_selector_info if isinstance(field_selector_info, str) else field_selector_info.get('selector')
                            attr = field_selector_info.get('attribute') if isinstance(field_selector_info, dict) else None
                            
                            try:
                                # Find element within the context of the current item if possible, 
                                # but deterministic selectors are often absolute or relative to a container.
                                # For this standalone script, we'll use the nth element of each selector.
                                el = await page.query_selector_all(field_selector)
                                if i < len(el):
                                    if attr:
                                        item[field] = await el[i].get_attribute(attr)
                                    else:
                                        item[field] = await el[i].inner_text()
                                    
                                    if item[field]:
                                        item[field] = item[field].strip()
                                else:
                                    item[field] = None
                            except Exception as e:
                                item[field] = None
                        
                        if any(item.values()):
                            extracted_items.append(item)
        
        await browser.close()
        return extracted_items

async def main():
    url = "{url}"
    data = await scrape_page(url)
    
    print(f"\\nExtracted {{len(data)}} items:")
    print(json.dumps(data, indent=2))
    
    # Save to file
    with open("extracted_data.json", "w") as f:
        json.dump(data, f, indent=2)
    print("\\nResults saved to extracted_data.json")

if __name__ == "__main__":
    asyncio.run(main())
'''
        return script
